### Processes shared memory

In [46]:
import multiprocessing as mp
import numpy as np
import ctypes

In [45]:
sharedData = np.zeros((4, 4))

In [47]:
_data = mp.Array(ctypes.c_double, 4*4)
sharedData = np.ctypeslib.as_array(_data.get_obj()).reshape(4,4)


In [48]:
def workerFunction (i):
    global sharedData
    sharedData[i, :] = i + 100

In [49]:
def testSharedMemory():
    pool = mp.Pool(processes = 4)
    pool.map(workerFunction, range(3))    

In [50]:
testSharedMemory ()

[[ 100.  100.  100.  100.]
 [ 101.  101.  101.  101.]
 [ 102.  102.  102.  102.]
 [   0.    0.    0.    0.]][[ 100.  100.  100.  100.]
 [ 101.  101.  101.  101.]
 [ 102.  102.  102.  102.]
 [   0.    0.    0.    0.]]

[[ 100.  100.  100.  100.]
 [ 101.  101.  101.  101.]
 [ 102.  102.  102.  102.]
 [   0.    0.    0.    0.]]





In [51]:
print(sharedData)

[[ 100.  100.  100.  100.]
 [ 101.  101.  101.  101.]
 [ 102.  102.  102.  102.]
 [   0.    0.    0.    0.]]
